"""adds Planet model

Revision ID: 71de1d53933e
Revises: 
Create Date: 2023-05-01 13:28:03.748198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71de1d53933e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('mass', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('moons', sa.Integer(), nullable=False),
    sa.Column('distance_from_sun', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('surface_area', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('namesake', sa.String(), nullable=False),
    sa.Column('visited_by_humans', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mass', sa.NUMERIC(precision=8, scale=3), autoincrement=False, nullable=True),
    sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_from_sun', sa.NUMERIC(precision=8, scale=3), autoincrement=False, nullable=True),
    sa.Column('surface_area', sa.NUMERIC(precision=8, scale=3), autoincrement=False, nullable=True),
    sa.Column('namesake', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('visited_by_humans', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planet_pkey')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###
